### PR TITLE
Better isolation of sandboxed environments

### PR DESCRIPTION
**Pull request by WSSDude420**
This PR prevents users from overwriting tables of another mod by accident.

Deep copying is avoided inside LuaSandbox::Initialize on purpose, as that function just creates base templated environment for each Sandbox instance. Sandbox instance makes deep copy during construction.

Deep copy does not take into account duplicates, which should not really happen in our use case I believe. Did not found anything which would break cause of wrong copy.
We do not deep copy keys, so keys which are tables will not get properly copied (we do this only inside DeepCopySolObject function), but again, should not matter for our use case. Can be added relatively easily if required, have previous code saved which had this function in.

Before this, something like this could be done, affecting other mods in the process:
```lua
ImGui.Begin = function(name) spdlog.info("PWND!") end
```

Didnt test the snippet, may be wrong, but you get the picture...

Cleaned-up version of #522 

---------------------

Also adds Double inside meta visitor of Converter ( @psiberx )

### CODE REVIEW

**Comment by psiberx** [comment]
Alongside deep copy this PR adds extra protection for usertypes (`Vector4`, `Enum`, etc.) and userdatas (main `Game` instance) that are shared between mod environments. This prevents adding new properties, overriding existing properties, and manipulating metatables.

An example of what was possible before PR:
```lua
getmetatable(Game).__index = function() 
    print('pwnd') 
    return function() end
end

Game.GetPlayer() -- pwnd
Game.GetStatsSystem() -- pwnd
```

**Comment by bonanov** [comment]
So, does this PR breaks the only way for mods to talk to each other?

**Comment by WSSDude420** [comment]
@bonanov no?

GetMod is still there and functions in exactly the same way.

This was done to prevent accidentaly screwing environment for other mods. If you need to communicste with some mod, you should have used GetMod, which was and still is there.

**Comment by bonanov** [comment]
@WSSDude420 oh, i was not aware of GetMod. Thank you!

**Pull request merged**
