### PR TITLE
More descriptive error log for unrecognized game version + build instructions

### PR DESCRIPTION
**Pull request by Murzinio**
Current message is a bit cryptic so I thought you could use something easier to understand.

### CODE REVIEW

**Review by yamashi — APPROVED** [review]

**Comment by Murzinio** [comment]
Also added build instructions to readme.

**Comment by yamashi** [comment]
The build instructions are too oriented, I don't think any of us use VScode with xmake, I expect most people contributing to this code base already have their preferences when it comes to tooling so this seems a bit excessive

**Comment by Murzinio** [comment]
Sure, you can use a bunch of different editors/IDEs. This is only showing a suggestion, no one will be forced to use VS Code. 

It's not for people already contributing as they already know how to build the project but a starting point for people that want to help.

**Comment by yamashi** [comment]
But we already have BUILD.md that does exactly that in way more details

**Comment by Murzinio** [comment]
Sorry, missed that - I assumed it will be in the readme file.

**Comment by Murzinio** [comment]
Removed the readme change.

**Review by yamashi — APPROVED** [review]

**Pull request merged**
