### PR TITLE
added TweakDB::SetFlats

### PR DESCRIPTION
**Pull request by Sombra0xCC**
TweakDB QoL
```lua
TweakDB:SetFlats('Character.Judy', {
  level = 99,
  tags = { 'Immortal' }
});
```

### CODE REVIEW

**Comment by Sombra0xCC** [comment]
don't merge. aObject.is<uint64_t> is not working...

**Comment by Sombra0xCC** [comment]
some problems with s64/u64:
1) can't check if the lua object is s64/u64, passing wrong data throws exception in strtoll
2) cant be casted to other int types
pic

other than that, everything is working.
Trying to convert an 'int' to 'string' now returns nullptr instead of throwing sol errors

**Comment by psiberx** [comment]
It's a LuaJIT specifics. Lua 5.1 supports only doubles and no int64s. LuaJIT implements them as special cdata structure. It's so non-standard you can't even check for that type using sol. But it can be done using Lua API directly. 
The casting though might be done without checks with applying Lua's `tonumber()` first to get the double from cdata, and then casting the result.

**Comment by psiberx** [comment]
I can merge this (eliminate CheckObjectType) with my changes to LuaRED to avoid conflict. 
And add the other way conversion (int64s to numbers).
Cyberpunk 2077 (C) 2020 by CD Projekt RED 05 05 21 19_36_18
`AssignedIndex` is `Int32`

**Comment by Sombra0xCC** [comment]
@psiberx That would be great
i removed my LuaRED changes

**Pull request merged**
