### PR TITLE
Save Lock Bypass 

### PR DESCRIPTION
**Pull request by dirtydanisreal**
a rough implementation. May or may not work.

credit to axstin

https://github.com/axstin/cyberpunk-things/tree/master/save-lock-bypass

### CODE REVIEW

**Comment by WSSDude420** [comment]
You forgot to actually call it and initialize it inside Initialize function found in dllmain.cpp

Of course, do so only when option is enabled.

**Review by WSSDude420 — CHANGES_REQUESTED** [review]
And where is this actually called? :)

Please, fix this issue.

**Comment by WSSDude420** [comment]
I hate this review system lol... First time testing it... Sucks balls

**Comment by WSSDude420** [comment]
Anyway... Please, also match name of patch with option name, Every patch does this if you look at them, keep same style.

**Comment by WSSDude420** [comment]
Look here for reference on these, as I messed up whole review...

This is what you should do.

One note though - wanted to try it, but it crashes my game when I try to save in combat.
Was it even tested properly?

**Comment by dirtydanisreal** [comment]
> Look here for reference on these, as I messed up whole review...
> [WSSDude420@55a2375](https://github.com/WSSDude420/CyberEngineTweaks/commit/55a237598af0f9c43e883b35fa0f258866d4001f)
> 
> This is what you should do.
> 
> One note though - wanted to try it, but it crashes my game when I try to save in combat.
> Was it even tested properly?

Sorry I wasn't able to get the project to compile for some reason, and I added it just before I had to leave for work. I tried xmake and it built the project but it wouldn't compile. Ill fix the call issue in the morning

**Comment by WSSDude420** [comment]
Sure no problem :)

Regarding building, we can try to help you resolve it.
Making PRs with untested code is not the best thing to do :P

Also, I dont know if you can change it now when you already created it... But may be nice to make this a draft to see that this is not yet finished.

If it cannot be changed now, well... Keep this in mind for the future :)

Unfinished WIP PRs - drafts.
Finished work PRs - regular.

**Comment by dirtydanisreal** [comment]
> Sure no problem :)
> 
> Regarding building, we can try to help you resolve it.
> Making PRs with untested code is not the best thing to do :P
> 
> Also, I dont know if you can change it now when you already created it... But may be nice to make this a draft to see that this is not yet finished.
> 
> If it cannot be changed now, well... Keep this in mind for the future :)
> 
> Unfinished WIP PRs - drafts.
> Finished work PRs - regular.

Yeah this is my first PR. Ill try to build it when I get home. Thank you for your patience.

**Comment by yamashi** [comment]
Appears dead, feel free to reopen if you finish it :)

**Pull request closed without merging**
